networks:
  codemeter-network:
    external: false
    driver: bridge
    attachable: true

services: 
  codemeter_license_service:
    build: 
      context: ./wibu/
      dockerfile: CodeMeter.Dockerfile
    image: wibu/codemeter:base
    container_name: CmLicenseService
    hostname: codemeter_license_service
    restart: unless-stopped
    entrypoint: [ "/usr/sbin/CodeMeterLin", "-v", "-l+", "-n-" ]
    volumes:
      - cm_config_volume:/etc/wibu/CodeMeter
      - cm_license_volume:/var/lib/CodeMeter/CmAct
      - /var/run/docker.sock:/var/run/docker.sock 
      - ./wibu/licenses:/.wibu
    networks:
      - codemeter-network
    # The following are recommendations by Wibu
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '75MB'
        reservations:
          cpus: '0.25'
          memory: '35MB'

  
  codemeter_webadmin:
    # If you don't need the WebAdmin tool, you can remove this container
    build: 
      context: ./wibu/
      dockerfile: CmWebAdmin.Dockerfile
    image: wibu/codemeter:webadmin
    container_name: CmWebAdmin
    hostname: codemeter_webadmin
    restart: unless-stopped
    environment:
      CODEMETER_HOST: codemeter_license_service
    volumes:
      - cm_config_volume:/etc/wibu/CodeMeter
    ports:
      - "22080:22352"
      - "22443:22353"
    networks:
      - codemeter-network
    depends_on:
      - codemeter_license_service
    # The following are recommendations by Wibu
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '75MB'
        reservations:
          cpus: '0.25'
          memory: '20MB'

  moryx:
    build: # Build the docker image from the code
      context: ./
      dockerfile: ./src/Example.App/Dockerfile
    image: moryx/example:latest
    container_name: moryx
    restart: unless-stopped
    ports: # Adjust the mapped ports to match your use case
      - "8080:8080"
      - "8081:8081"
    environment: # We need to set this env variable for the Wibu dependencies to work
      CODEMETER_HOST: codemeter_license_service
    volumes: # Persiting the configs and logs 
      - moryx-config:/app/Config
      - moryx-logs:/app/Logs
    networks: # In addition to the default network we need to put our app into the network of the codemeter container
      - default
      - codemeter-network
    depends_on:
      - codemeter_license_service
      
volumes:
  moryx-logs:
  moryx-config:
  cm_config_volume: 
    driver: local
    external: false
    labels:
      description: "CodeMeter Config Volume"
  
  cm_license_volume:
    driver: local
    external: false
    labels:
      description: "CodeMeter CmAct License Volume"
